Никитин Александр
VK-BMSTU-QA/selenium-seminar-autumn2024 pull request #20
Opened 2024-10-26 23:33 UTC by Olegsandrik

2024-10-27 08:05 UTC, FunnyRockfish approved these changes
Вроде всё окей - ничего серьёзного не нашёл

2024-10-27 08:20 UTC, oFem1m approved these changes
Я бы удалил из комита бинарники, в остальном нормально, проблем не вижу, аппрув

2024-11-06 13:33 UTC, BeeHeather requested changes
Привет! Оставила комменты, основное:
1) добавь обработку ошибок 
2) замени time.sleep на явные ожидания
3) распиши шаги в аллюре более подробно

2024-11-06 13:33 UTC, BeeHeather commented on Selenium/code/test_login.py
>  @pytest.fixture(scope='session')
Мб удалим пустую фикстуру? Раз она не используется

2024-11-06 13:33 UTC, BeeHeather commented on Selenium/code/ui/pages/base_page_VK.py
> +        while time.time() - started < timeout:
Какая-то сложная логика. Давай сделаем проще, через WebDriverWait.until

2024-11-06 13:33 UTC, BeeHeather commented on Selenium/code/ui/pages/base_page_VK.py
> +        self.find(locator, timeout=timeout)
Это избыточная проверка

2024-11-06 13:33 UTC, BeeHeather commented on Selenium/code/ui/pages/base_page_VK.py
> +        assert 1 == 1
А ето who, давай удалим

2024-11-06 13:33 UTC, BeeHeather commented on Selenium/code/ui/pages/base_page_VK.py
> +    def input(self, input_field, data):
Давай добавим еще очищение поля ввода

2024-11-06 13:33 UTC, BeeHeather commented on Selenium/code/ui/pages/base_page_VK.py
> +    @allure.step('input')
Предлагаю сделать более подробное описание шагов здесь и далее, для того чтобы отчет в аллюре был понятным

2024-11-06 13:33 UTC, BeeHeather commented on Selenium/code/ui/pages/base_page_VK.py
> +        return self.wait(timeout).until(EC.presence_of_element_located(locator))
Я бы еще везде добавила обработку ошибок через TimeoutException с описанием (чтобы в отчете было понятно, в какой момент и почему тест упал)

2024-11-14 20:28 UTC, Olegsandrik commented on Selenium/code/test_login.py
> +        time.sleep(3)
убрал

2024-11-14 20:28 UTC, Olegsandrik commented on Selenium/code/test_login.py
> +    return {
сделал

2024-11-14 20:28 UTC, Olegsandrik commented on Selenium/code/test_login.py
> +        self.driver.get('https://education.vk.company/feed/')
добавил конфиг

2024-11-14 20:29 UTC, Olegsandrik commented on Selenium/code/ui/pages/base_page_VK.py
> +        while time.time() - started < timeout:
это логика с репы препа, я ее просто скопировал

2024-11-14 20:30 UTC, Olegsandrik commented on Selenium/code/ui/pages/base_page_VK.py
> +        self.find(locator, timeout=timeout)
убрал

2024-11-14 20:30 UTC, Olegsandrik commented on Selenium/code/ui/pages/base_page_VK.py
> +        assert 1 == 1
удалил

2024-11-14 20:30 UTC, Olegsandrik commented on Selenium/code/ui/pages/base_page_VK.py
> +    def input(self, input_field, data):
добавил

2024-11-14 20:30 UTC, Olegsandrik commented on Selenium/code/ui/pages/base_page_VK.py
> +    @allure.step('input')
Сделал более подробно

2024-11-15 01:25 UTC, BeeHeather requested changes

2024-11-15 01:25 UTC, BeeHeather commented on Selenium/code/ui/pages/base_page_VK.py
> +            print(f'TimeoutException')
Давай здесь ошибку опишем, что-то вроде "Элемент не был найден"

2024-11-15 01:25 UTC, BeeHeather commented on Selenium/code/test_login.py
>  @pytest.fixture(scope='session')
еще актуально ^

2024-11-15 15:02 UTC, Olegsandrik commented on Selenium/code/ui/pages/base_page_VK.py
> +            print(f'TimeoutException')
Сделал

2024-11-17 22:12 UTC, BeeHeather approved these changes
Замечания исправлены
Аппрув, 5 баллов

2025-02-02 22:41 UTC, closed without merging